# Generated by Django 2.2.3 on 2019-09-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_company_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
