# Generated by Django 2.0.5 on 2019-07-12 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('range', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('goal', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('job', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('otherservice', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('client_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('request_status', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('agency_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
