# Generated by Django 2.0.5 on 2019-07-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestBrief', '0002_event_request_client_remote_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_request',
            name='client_remote_work',
        ),
    ]
