# Generated by Django 2.0.5 on 2019-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestBrief', '0003_remove_event_request_client_remote_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_request',
            name='client_remote_work',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
