# Generated by Django 2.0.5 on 2019-07-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestBrief', '0005_event_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_message',
            name='agency_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
