# Generated by Django 2.0.5 on 2019-07-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestBrief', '0006_event_message_agency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_request',
            name='request_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
