# Generated by Django 2.0.5 on 2019-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('happy', models.FloatField(blank=True, default=None, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
