# Generated by Django 2.0.5 on 2019-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_favorite',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1, null=True),
        ),
    ]
