# Generated by Django 2.0.5 on 2019-07-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190714_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='review',
        ),
    ]
