# Generated by Django 2.1 on 2019-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190902_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Average',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1, null=True),
        ),
    ]
