# Generated by Django 2.0.5 on 2019-07-12 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_username', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('agent_email', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('agency_company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_company_website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_establish_time', models.IntegerField(blank=True, default='', null=True)),
                ('agency_employee_number', models.IntegerField(blank=True, default='', null=True)),
                ('agency_annual_turnover', models.IntegerField(blank=True, default='', null=True)),
                ('agency_member_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_description', models.CharField(blank=True, default='', max_length=2083, null=True)),
                ('agency_logo', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('agency_language', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_contact_number', models.IntegerField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agency_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_company_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_social_media', models.CharField(blank=True, default=None, max_length=2083, null=True)),
                ('agency_past_work', models.CharField(blank=True, default='', max_length=2083, null=True)),
                ('agency_upcoming_work', models.CharField(blank=True, default='', max_length=2083, null=True)),
                ('agency_provide_design', models.CharField(blank=True, default='', max_length=2083, null=True)),
                ('agent_username', models.CharField(default='', max_length=255)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBrief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_specialty', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_interest', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_remote_work', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency_budget_upper', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('agent_username', models.CharField(default='', max_length=255)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_designation', models.CharField(max_length=255)),
                ('staff_email', models.CharField(max_length=255)),
                ('agent_username', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
