# Generated by Django 2.0.5 on 2019-07-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybrief',
            name='agency_budget_lower',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
