# Generated by Django 2.0.5 on 2019-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20190712_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybrief',
            name='agency_budget_lower',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='agencybrief',
            name='agency_budget_upper',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
