# Generated by Django 2.0.5 on 2019-07-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20190713_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybrief',
            name='agency_budget_lower',
        ),
        migrations.RemoveField(
            model_name='agencybrief',
            name='agency_budget_upper',
        ),
    ]
