# Generated by Django 2.0.5 on 2019-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20190713_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybrief',
            name='agency_budget_lower',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencybrief',
            name='agency_budget_upper',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
