# Generated by Django 2.0.5 on 2019-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20190713_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_studio_size',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
