# Generated by Django 2.0.5 on 2019-07-13 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agency_agency_studio_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
