# Generated by Django 2.0.5 on 2019-07-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_agency_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybrief',
            name='agency_budget_upper',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
