# Generated by Django 2.0.5 on 2019-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_agencybrief_agency_budget_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybrief',
            name='agency_budget_lower',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
