# Generated by Django 2.0.5 on 2019-07-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_agencybrief_agency_budget_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency_info',
            name='agency_service_provider',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
