# Generated by Django 2.2.3 on 2019-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_agency_info_agency_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_past_work',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
