# Generated by Django 2.0.5 on 2019-07-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=2080)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('uploader', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
