# Generated by Django 2.0.5 on 2019-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_name',
            field=models.CharField(blank=True, default=None, max_length=2080, null=True),
        ),
    ]
