# Generated by Django 2.0.5 on 2019-07-20 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminagency_transaction',
            name='admin_agency_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_address_division',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_billing_email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_country',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_postal_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agency_vat_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agent_first_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agent_last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='agent_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminagency_transaction',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='adminagency_transaction',
            name='admin_agency_pay_method',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminagency_transaction',
            name='admin_agency_pay_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
