# Generated by Django 2.0.5 on 2019-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190720_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminagency_transaction',
            name='agency_card_month',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
