# Generated by Django 2.2.3 on 2019-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stuff',
        ),
        migrations.AddField(
            model_name='event',
            name='event_client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
