# Generated by Django 2.2.3 on 2019-09-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190902_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_secured',
            field=models.BooleanField(default=False),
        ),
    ]
